# **NUMPY BASICS**

# Introduction

## What is NumPy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ```ndarray``` object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

The main reason why conputation using NumPy arrays is **vectorization** i.e., absence of any explicit looping, indexing, etc., in the code.These things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code.

## Key Terms

### ```ndarray``` and Axes

NumPy’s main object is the homogeneous multidimensional array, called the . It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

For example, the array for the coordinates of a point in 3D space, [1, 2, 1], has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

``` py
[[1., 0., 0.],
 [0., 1., 2.]]
 ```

### Attributes of ```ndarray```

NumPy’s array class is called ```ndarray```. It is also known by the alias ```array```. Note that ```numpy.array``` is not the same as the Standard Python Library class ```array.array```, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ```ndarray``` object are:

- ```ndarray.ndim```: the number of axes (dimensions) of the array.

- ```ndarray.shape```: a tuple of integers indicating the size (length) of the array in each dimension.

- ```ndarray.size```: the total number of elements of the array. Equal to the product of the elements of ```shape```.

- ```ndarray.dtype```: an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. 

- ```ndarray.itemsize```: the size in bytes of each element of the array. Equivalent to ```ndarray.dtype.itemsize```.

- ```ndarray.data```: the buffer containing the actual elements of the array. Better to use indexing to access elements.

Consider the following example to understand these attributes:

In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)

print("a:\n", a)
print()
print("a.shape: ", a.shape)
print("a.ndim: ", a.ndim)
print("a.dtype.name: ", a.dtype.name)
print("a.itemsize: ", a.itemsize)
print("a.size: ", a.size)
print("type(a): ", type(a))

a:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

a.shape:  (3, 5)
a.ndim:  2
a.dtype.name:  int64
a.itemsize:  8
a.size:  15
type(a):  <class 'numpy.ndarray'>


# Basics of ```ndarray```

## Creating Arrays

### Arrays from python lists and tuples

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)

arr1:
[1 2 3 4 5]

arr2:
[[1 2 3]
 [4 5 6]]


### Arrays with specific data types

In [5]:
arr3 = np.array([1, 2, 3], dtype=float)
arr4 = np.array([1.2, 2.7, 3.9], dtype=int)

print("arr3 (float):")
print(arr3)
print("\narr4 (int, truncated):")
print(arr4)

arr3 (float):
[1. 2. 3.]

arr4 (int, truncated):
[1 2 3]


### Arrays filled with zeros, ones, or a constant

In [6]:
zeros_arr = np.zeros((3, 4))
ones_arr = np.ones((2, 3))
full_arr = np.full((3, 3), 7)

print("zeros_arr:")
print(zeros_arr)
print("\nones_arr:")
print(ones_arr)
print("\nfull_arr:")
print(full_arr)

zeros_arr:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones_arr:
[[1. 1. 1.]
 [1. 1. 1.]]

full_arr:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Creating sequences using ranges

In [17]:
range_arr1 = np.arange(0, 10)
range_arr2 = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 2*np.pi, 10)       # useful to evaluate function at lots of points

print("range_arr1:")
print(range_arr1)
print("\nrange_arr2:")
print(range_arr2)
print("\nlinspace_arr:")
print(linspace_arr)

range_arr1:
[0 1 2 3 4 5 6 7 8 9]

range_arr2:
[0 2 4 6 8]

linspace_arr:
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


> **NOTE:** When ```arange``` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the *finite floating point precision*. For this reason, it is usually better to use the function ```linspace``` that receives as an argument the number of elements that we want, instead of the step.

### Identity and diagonal matrices

In [8]:
identity_arr = np.eye(4)
diag_arr = np.diag([1, 2, 3, 4])

print("identity_arr:")
print(identity_arr)
print("\ndiag_arr:")
print(diag_arr)

identity_arr:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

diag_arr:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### Randomly generated arrays

In [9]:
rand_arr1 = np.random.rand(3, 3)
rand_arr2 = np.random.randn(3, 3)
rand_arr3 = np.random.randint(1, 10, size=(3, 3))

print("rand_arr1 (uniform [0,1)):")
print(rand_arr1)
print("\nrand_arr2 (normal distribution):")
print(rand_arr2)
print("\nrand_arr3 (random integers):")
print(rand_arr3)

rand_arr1 (uniform [0,1)):
[[0.9388036  0.11754516 0.48279295]
 [0.85982873 0.1774632  0.97103   ]
 [0.25925656 0.19208806 0.5834702 ]]

rand_arr2 (normal distribution):
[[-2.07516399 -0.66933274  0.73359982]
 [-0.78282426  0.23332169  1.09594627]
 [ 1.367237   -0.30998706  0.78880593]]

rand_arr3 (random integers):
[[4 4 8]
 [2 4 9]
 [2 1 4]]


### Empty arrays (uninitialized values)

In [10]:
empty_arr = np.empty((2, 3))
print("empty_arr:")
print(empty_arr)

empty_arr:
[[1. 1. 1.]
 [1. 1. 1.]]


### Arrays based on an existing array

In [11]:
base_arr = np.array([10, 20, 30])
zeros_like_arr = np.zeros_like(base_arr)
ones_like_arr = np.ones_like(base_arr)
full_like_arr = np.full_like(base_arr, 99)

print("base_arr:")
print(base_arr)
print("\nzeros_like_arr:")
print(zeros_like_arr)
print("\nones_like_arr:")
print(ones_like_arr)
print("\nfull_like_arr:")
print(full_like_arr)

base_arr:
[10 20 30]

zeros_like_arr:
[0 0 0]

ones_like_arr:
[1 1 1]

full_like_arr:
[99 99 99]


### Creating arrays from string data

In [12]:
str_arr = np.fromstring("1 2 3 4 5", sep=" ")
print("str_arr:")
print(str_arr)

str_arr:
[1. 2. 3. 4. 5.]


### Meshgrid (useful in numerical computing and ML)

In [13]:
x = np.linspace(0, 1, 3)
y = np.linspace(0, 1, 3)
X, Y = np.meshgrid(x, y)

print("x:")
print(x)
print("\ny:")
print(y)
print("\nX grid:")
print(X)
print("\nY grid:")
print(Y)


x:
[0.  0.5 1. ]

y:
[0.  0.5 1. ]

X grid:
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]

Y grid:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


## Operating on Arrays

### Printing arrays

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
- the last axis is printed from left to right,
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

> **NOTE:** If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners

### Arithmetic Opereations

Arithmetic operations on arrays apply *elementwise*. A new array is created and filled with the result. Unlike many matrix languages, the product operator ```*``` applies elementwise in NumPy array. In order to perform matrix product, use ```@``` operator or the ```.dot()``` method.

**NOTE:**
- Some operations, such as ```+=``` and ```/=```, act in place to modify the existing array instead of creating a new array.
- When operationg on arrays of different types, the type of resulting array corrosponds to the more general or precise one (this behavior is called **upcasting**).

In [25]:
# Basic arithmetic operations
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print("a: ", a)
print("b: ", b)
print("a - b: ", a-b)
print("b**2: ", b**2)

c = 10 * np.sin(a)
print("c: ", c)

d = a < 35
print("d: ", d)

a:  [20 30 40 50]
b:  [0 1 2 3]
a - b:  [20 29 38 47]
b**2:  [0 1 4 9]
c:  [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
d:  [ True  True False False]


In [24]:
# Matrix Product
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

C = A*B         # Elementwise product
print("A * B:\n", C)
print()
D = A@B         # Matrix product; alternatively use A.dot(B)
print("A @ B:\n", D)

A * B:
 [[2 0]
 [0 4]]

A @ B:
 [[5 4]
 [3 4]]


Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ```ndarray``` class. By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the ```axis``` parameter you can apply an operation along the specified axis of an array:

In [33]:
a = np.random.rand(5)
print(a)

print("Sum: ", a.sum())
print("Max: ", a.max())
print()

b = np.arange(12).reshape(3, 4)
print("b:\n", b)
print("Sum of each column: ", b.sum(axis=0))
print("Min of each row: ", b.min(axis=1))
print("Cumilative sum along each row:\n", b.cumsum(axis=1))


[0.90207076 0.13225208 0.01479491 0.08622977 0.02301403]
Sum:  1.1583615400462381
Max:  0.9020707556213127

b:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sum of each column:  [12 15 18 21]
Min of each row:  [0 4 8]
Cumilative sum along each row:
 [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


### Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (```ufunc```). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [38]:
B = np.arange(3)
print("B:\t\t", B)
print("np.exp(B):\t", np.exp(B))
print("np.sqrt(B):\t", np.sqrt(B))

C = np.array([2., -1., 4.])
print("np.add(B, C):\t", np.add(B, C))

B:		 [0 1 2]
np.exp(B):	 [1.         2.71828183 7.3890561 ]
np.sqrt(B):	 [0.         1.         1.41421356]
np.add(B, C):	 [2. 0. 6.]


### Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [26]:
# One dimensional arrays
a = np.arange(10)**3
print("a:\t\t\t", a)

print("a[2]:\t\t\t", a[2])
print("a[2:5]:\t\t\t", a[2:5])

a[:6:2] = 1000          # from start to position 6, exclusive, set every 2nd element to 1000
print("a:\t\t\t", a)

print("reversed a (a[::-1])\t", a[::-1])

a:			 [  0   1   8  27  64 125 216 343 512 729]
a[2]:			 8
a[2:5]:			 [ 8 27 64]
a:			 [1000    1 1000   27 1000  125  216  343  512  729]
reversed a (a[::-1])	 [ 729  512  343  216  125 1000   27 1000    1 1000]


Multidimension arrays can have one index per axis. These indices are given in a tuple separated by commas.

**NOTE:**
- When fewer indices are provided than the number of axes, the missing indices are considered complete slices ```:```
- The expression within brackets in ```b[i]``` is treated as an ```i``` followed by as many instances of ```:``` as needed to represent the remaining axes. NumPy also allows you to write this using dots as ```b[i, ...]```.

The dots (```...```) represent as many colons as needed to produce a complete indexing tuple. For example, if ```x``` is an array with 5 axes, then:
- ```x[1, 2, ...]``` is equivalent to ```x[1, 2, :, :, :]```,
- ```x[..., 3]``` to ```x[:, :, :, :, 3]``` and
- ```x[4, ..., 5, :]``` to ```x[4, :, :, 5, :]```.

In [27]:
# Multi-dimensional arrays
b = np.arange(20).reshape(5, 4)**2
print("b:\n", b)
print()

print("b[2,3] = \t", b[2,3])
print("b[0:5, 1] =\t", b[0:5, 1])    # each row in the second column of b
print()

print("b[1:3, :]\n", b[1:3, :])
print()

print("b[-1]: ", b[-1])

b:
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]]

b[2,3] = 	 121
b[0:5, 1] =	 [  1  25  81 169 289]

b[1:3, :]
 [[ 16  25  36  49]
 [ 64  81 100 121]]

b[-1]:  [256 289 324 361]


In [36]:
c = np.arange(24).reshape(2, 3, 4)**2
print("c:\n", c)

c:
 [[[  0   1   4   9]
  [ 16  25  36  49]
  [ 64  81 100 121]]

 [[144 169 196 225]
  [256 289 324 361]
  [400 441 484 529]]]
